//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigurnostCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
        public int tipKorisnika { get; set; }
        public string mail { get; set; }
    
        public virtual TipKorisnika TipKorisnika1 { get; set; }

        //public Korisnik(int id, string ime, string prezime, string korisnickoIme, string lozinka, int tipKorisnika, string mail)
        //{
        //    this.id = id;
        //    this.ime = ime;
        //    this.prezime = prezime;
        //    this.korisnickoIme = korisnickoIme;
        //    this.lozinka = lozinka;
        //    this.tipKorisnika = tipKorisnika;
        //    this.mail = mail;
        //}
    }
}
